package ru.kyamshanov.missionChat.domain.models

import kotlinx.datetime.LocalDateTime

/**
 * Represents a message within a chat inference session.
 * This sealed interface defines the various types of messages that can occur in a conversation,
 * including system instructions, human inputs, assistant responses, and tool interactions.
 */
sealed interface MessageInference {

    /**
     * Unique identifier for the message.
     */
    val id: Identifier

    /**
     * The textual content of the message.
     */
    val text: String

    /**
     * The timestamp when the message was created.
     */
    val createdAt: LocalDateTime

    /**
     * Represents a system-level instruction or context message.
     *
     * @property id Unique identifier.
     * @property text The content of the system message.
     * @property createdAt Timestamp of creation.
     * @property associatedHuman Optional human context associated with this system message.
     */
    data class SystemMessage(
        override val id: Identifier,
        override val text: String,
        override val createdAt: LocalDateTime,
        val associatedHuman: Interlocutor.Human? = null
    ) : MessageInference

    /**
     * Represents a message sent by a human user.
     *
     * @property id Unique identifier.
     * @property text The user's input text.
     * @property createdAt Timestamp of creation.
     * @property human The human interlocutor who sent the message.
     * @property availableTools List of tools available for the assistant to use in response to this message.
     */
    data class HumanMessage(
        override val id: Identifier,
        override val text: String,
        override val createdAt: LocalDateTime,
        val human: Interlocutor.Human,
        val availableTools: List<ToolEnum> = emptyList(),
    ) : MessageInference

    /**
     * Represents a response generated by the AI assistant.
     *
     * @property id Unique identifier.
     * @property text The assistant's response text.
     * @property createdAt Timestamp of creation.
     * @property associatedHuman Optional human context for the response.
     */
    data class AssistantMessage(
        override val id: Identifier,
        override val text: String,
        override val createdAt: LocalDateTime,
        val associatedHuman: Interlocutor.Human? = null,
    ) : MessageInference

    /**
     * Represents an assistant's intent to call a specific tool/function.
     *
     * @property id Unique identifier.
     * @property tool The tool being called.
     * @property createdAt Timestamp of creation.
     * @property associatedHuman Optional human context.
     * @property responseStartWith Optional prefix.
     * @property text Raw text from LLM containing the function call details.
     */
    data class AssistantFunctionCalling(
        override val id: Identifier,
        val tool: ToolEnum,
        override val createdAt: LocalDateTime,
        val associatedHuman: Interlocutor.Human? = null,
        val responseStartWith: String? = null,
        override val text: String,
    ) : MessageInference

    /**
     * Represents the result/output returned from a tool execution.
     *
     * @property tool The tool that was executed.
     * @property id Unique identifier.
     * @property text The result of the function call.
     * @property createdAt Timestamp of creation.
     */
    data class FunctionCallingResponse(
        val tool: ToolEnum,
        override val id: Identifier,
        override val text: String,
        override val createdAt: LocalDateTime,
    ) : MessageInference
}